-- PRODUCT_CODE :UNIQUE, 앞2자리 카테고리
-- 상품코드 별 매출액(판매가 * 판매량) 합계
-- 상품코드, 매출액 => 상품코드 별 매출액
WITH TEMP (PRODUCT_CODE, TOTAL)
AS
(
SELECT   
      P.PRODUCT_CODE AS PRODUCT_CODE
    , S.SALES_AMOUNT * P.PRICE AS TOTAL
FROM OFFLINE_SALE S
INNER JOIN PRODUCT P ON S.PRODUCT_ID = P.PRODUCT_ID
)
SELECT
      PRODUCT_CODE
    , SUM(TOTAL) AS SALES
FROM TEMP 
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE;
