--제외할 car_id 찾기
SELECT 
      DISTINCT C.car_id
    , C.car_type
    , C.DAILY_FEE * ((100 - P.DISCOUNT_RATE) * 30 * 0.01) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
LEFT OUTER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON P.CAR_TYPE = C.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV')AND C.CAR_ID NOT IN (
                        SELECT
                            CAR_ID
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                        WHERE 1 = 1
                        AND START_DATE BETWEEN TO_DATE('2022-11-01', 'YYYY-MM-DD') AND TO_DATE('2022-11-30', 'YYYY-MM-DD')
                        OR END_DATE BETWEEN TO_DATE('2022-11-01', 'YYYY-MM-DD') AND TO_DATE('2022-11-30', 'YYYY-MM-DD')
                        OR (START_DATE <= TO_DATE('2022-11-01', 'YYYY-MM-DD') AND END_DATE >= TO_DATE('2022-11-30', 'YYYY-MM-DD'))
                    )
AND P.DURATION_TYPE = '30일 이상'
AND C.DAILY_FEE * ((100 - P.DISCOUNT_RATE) * 30 * 0.01) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, car_type, CAR_ID DESC;
