--  음식종류별로 ...
WITH TEMP AS
(
SELECT 
    FOOD_TYPE,
    MAX(FAVORITES) AS FAVORITES
FROM REST_INFO
GROUP BY FOOD_TYPE
)
SELECT
    T.FOOD_TYPE,
    R.REST_ID,
    R.REST_NAME,
    T.FAVORITES AS FAVORITES
FROM REST_INFO R
INNER JOIN TEMP T
    ON R.FOOD_TYPE = T.FOOD_TYPE AND R.FAVORITES = T.FAVORITES
ORDER BY FOOD_TYPE DESC;