-- 코드를 입력하세요
-- ANIMAL_OUTS 에는 있는데  ANIMAL_INS에는 없는 ANIMAL_ID값, O.NAME 이렇게 출력
-- ->당연히 레코드별로 도는건 비효율적이고, outer join으로 처리
SELECT O.ANIMAL_ID
      ,O.NAME
FROM ANIMAL_OUTS O
WHERE NOT EXISTS(SELECT 1 FROM ANIMAL_INS I WHERE I.ANIMAL_ID = O.ANIMAL_ID)
ORDER BY O.ANIMAL_ID, O.NAME
;
