-- 코드를 입력하세요
-- 식품ID , 식품이름, 총매출
WITH ORDER_TEMP AS
(
SELECT 
    PRODUCT_ID,
    AMOUNT
FROM FOOD_ORDER 
WHERE 1 = 1
AND PRODUCE_DATE BETWEEN TO_DATE('2022-05-01', 'YYYY-MM-DD') AND TO_DATE('2022-05-31', 'YYYY-MM-DD')
)
SELECT 
    O.PRODUCT_ID,
    P.product_name,
    SUM(O.AMOUNT * P.PRICE) AS TOTAL_SALES
FROM ORDER_TEMP O 
LEFT OUTER JOIN FOOD_PRODUCT P  ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY O.PRODUCT_ID, P.product_name
HAVING SUM(O.AMOUNT * P.PRICE) IS NOT NULL
ORDER BY TOTAL_SALES DESC, O.PRODUCT_ID;
