-- 시간대 별 입양 건 수
SELECT 
     TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) HOUR
   , COUNT(ANIMAL_ID) COUNT
FROM ANIMAL_OUTS
GROUP BY TO_CHAR(DATETIME, 'HH24')
HAVING TO_CHAR(DATETIME, 'HH24') > 8 AND TO_CHAR(DATETIME, 'HH24') < 20
ORDER BY HOUR;