-- 시간대 별 입양 건 수
SELECT 
     DISTINCT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR
   , COUNT(ANIMAL_ID) OVER (PARTITION BY TO_CHAR(DATETIME, 'HH24')) AS COUNT
FROM ANIMAL_OUTS
WHERE TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) > 8 AND TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) < 20
ORDER BY HOUR;