-- 시간대 별 입양 건 수
SELECT 
     DISTINCT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR
   , COUNT(ANIMAL_ID) OVER (PARTITION BY TO_CHAR(DATETIME, 'HH24')) AS COUNT
FROM ANIMAL_OUTS
WHERE TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) > 8 AND TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) < 20
ORDER BY HOUR;


-- GROUP BY 가 더 친숙하긴 하지만, GROUP BY의 경우 성능이 좋지 못함 -> PARTITION BY를 활용하자!
-- 대신, PARTITION BY는 값 손실없이 나온다는점을 기억하고! DISTINCT를 활용
SELECT 
     TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) HOUR
   , COUNT(ANIMAL_ID) COUNT
FROM ANIMAL_OUTS
GROUP BY TO_CHAR(DATETIME, 'HH24')
HAVING TO_CHAR(DATETIME, 'HH24') > 8 AND TO_CHAR(DATETIME, 'HH24') < 20
ORDER BY HOUR;
