-- 진료과 코드별로 2022년 5월에 예약한 환자 수 
SELECT 
    MCDP_CD "진료과 코드",
    SUM(1) "5월예약건수"
FROM APPOINTMENT
WHERE APNT_YMD BETWEEN TO_DATE('2022-05-01','YYYY-MM-DD') AND TO_DATE('2022-05-31','YYYY-MM-DD')
GROUP BY MCDP_CD
ORDER BY "5월예약건수", MCDP_CD;