-- 코드를 입력하세요
-- 보호시작일 > 입양일 => 잘못된 데이터
SELECT 
      I.ANIMAL_ID
    , I.NAME
FROM ANIMAL_INS I 
INNER JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.DATETIME > O.DATETIME
ORDER BY I.DATETIME;