-- 코드를 입력하세요
SELECT
    BOOK_ID,
    TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
FROM BOOK
WHERE 1 = 1
AND EXTRACT(YEAR FROM PUBLISHED_DATE) = '2021'
AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE;


--성능을 고려한다면 좌변에 EXTRACT 함수를 사용하기보다는 이 방법이 더 나음
--만약 PUBLISHED_DATE에 인덱스가 걸려있는데, 가공을 거치면 인덱스를 안 탈 수 있음
SELECT
    BOOK_ID,
    TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
FROM BOOK
WHERE 1 = 1
AND PUBLISHED_DATE BETWEEN TO_DATE('2021-01-01', 'YYYY-MM-DD') AND TO_DATE('2021-12-29', 'YYYY-MM-DD')
AND CATEGORY = '인문'
ORDER BY PUBLISHED_DATE;
