-- SALES에서 ID별로 판매량 합산 -> 조인으로 카테고리 찾기
-- BOOK_ID가 카테고리가 아니기때문에, BOOK_SALES에서 먼저 집계한 다음 JOIN처리 불가!
-- JOIN으로 카테고리값 먼저 얻어낸 후 집계
SELECT 
    B.CATEGORY,
    SUM(S.SALES) AS TOTAL_SALES
FROM BOOK_SALES S
INNER JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
WHERE SALES_DATE BETWEEN TO_DATE('2022-01-01','YYYY-MM-DD') AND TO_DATE('2022-01-31', 'YYYY-MM-DD') 
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;